### PR TITLE
Stub all frameworks

### LINKED ISSUE #1: Missing frameworks
I currently don't have the time to debug if those frameworks work or not and if any further changes are necessary but while doing https://github.com/NixOS/nixpkgs/pull/102306 I noticed the following frameworks are missing here:

SDK 10.12 or earlier:
- Contacts
- ContactsUI
- CryptoTokenKit
- Intents
- NetworkExtension
- NotificationCenter
- Photos
- PhotosUI
- SafariServices

The following frameworks are added with later SDKs and are missing. We should probably wait until that SDK version is used to add them.

SDK 10.13:
- CoreML
- CoreSpotlight
- ExternalAccessory
- Vision

SDK 10.14:
- Network
- UserNotifications

SDK 10.15:
- AuthenticationServices
- OSLog
- PushKit
- Speech
- SystemExtensions

### PR DESCRIPTION
**Pull request by thefloweringash**
The initial version only included things used by nixpkgs. This adds all the frameworks from `/System/Library/Frameworks/*.framework`.

Fixes #1

### CODE REVIEW

**Comment by thefloweringash** [comment]
I don't know the exact ownership of this repository, but I don't want to just merge my own PRs.

cc @LnL7 @domenkozar who helped set this up.

**Comment by domenkozar** [comment]
I think it's fine to merge your own PRs if there's noone to review. I don't have macOS expertise so I'll refrain.

**Review by LnL7 — APPROVED** [review]
I glanced over this but didn't really review since it's mostly just generated content. But generating stubs for everything makes sense and means adding a missing framework doesn't require rebuilding everything.

**Comment by thefloweringash** [comment]
Looking at the linked pull request I realized that this should also include private frameworks.

**Pull request merged**
